language: php
php:
  - 7.3
  - 7.4
  - hhvm
  - nightly
before_install:
  - travis_retry composer self-update
  - composer install
script: ./vendor/phpunit/phpunit/phpunit --testdox --bootstrap vendor/autoload.php tests
